travis:
  secure:
    BINSTAR_TOKEN: R6xyWbDleW34C6N7FeJt3BtJrXqAgmSjhWMNhZzP51b8Y5X1ff8bdhRO929jiZaPlrkNDQjTmaasMDj3574wwPNuYR4wcaWD4Zr318zOHNYONuNHSKCaQKU69HgH4gly1RAU24nL+5zPNFcW8+iL9cUNxrhBsaNDVZaamutIXLkc2MP6uBQ92HfPTH9GMpMJ2J2JVqnXgQIq7G2zw5j3zV++Uu1Kkk9OW7AOqThvMx7dXlgw88VwCmukbRKH7uNttadsPsuIPrMNAhm9ROtm4MrIe28fatV8VBiZC7N7FvF4LhByQLSiukkDTPrCRT+GwYBgprT2SbX5jy0h6ySXRPRNS7HQKeKvWfdwWGYW6HymS1WjTRc3HfdOP7wiPe/yCNV9Qw8H8LFey9vMTeluzHZgPxiM1yKRI662HXOxzDyyjMImjQxxVwHEYB0zbQ/LTr4zdSP8A9F75sCPArX61kMGrAH2Ap6cUmcD97WVZmmF/15RMzavMUggUNCMA3wBk5gTp0j6lIgwKhOYiE6PN2EhwUChoeUEBfpa6l3e9TmDsEp40md/OC0yLYzA5AK75F1frMjegdXuoy+m0fTiKPqh5hptXeXXvC5kJLSJHVvB7tbHZN1LKz7IJbJxFq6iewLPfbKAOM64vgkV/OBcvGFo6MlcL7jJ5rGSGLSvZ8M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
